services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api.dev
    container_name: api
    # ports:
    #   - 3000:3000
    volumes:
      - .:/app
    depends_on:
       db:
        condition: service_healthy

  db:
    build:
      context: .
      dockerfile: docker/Dockerfile.db
    container_name: db
    environment:
      MYSQL_DATABASE: api
      MYSQL_USER: api
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root
    # ports:
    #   - 3308:3306
    volumes:
      - ./db-data:/var/lib/mysql:z
    # https://github.com/docker/compose/issues/9367
    healthcheck:
      test: "mysql -uroot -p$$MYSQL_ROOT_PASSWORD"
      interval: 10s
      timeout: 30s
      retries: 3

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    # ports:
    #   - 8000:8080

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.dev.Dockerfile
    container_name: nginx
    restart: always
    ports:
      # - 4200:4200
      - 80:80
    depends_on:
      - api