definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  model.User:
    properties:
      avatar:
        type: string
      created_at:
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      fullname:
        type: string
      id:
        type: integer
      password:
        type: string
      updated_at:
        type: string
      username:
        type: string
    required:
    - fullname
    - password
    - username
    type: object
  request.LoginRequest:
    properties:
      password:
        example: "1234"
        type: string
      username:
        example: admin
        type: string
    required:
    - password
    - username
    type: object
  request.Product:
    properties:
      amount:
        example: 10
        type: integer
      description:
        example: apple
        type: string
      name:
        example: apple
        type: string
      price:
        example: 200
        type: number
      sale_close_date:
        example: "2021-12-26T00:00:00Z"
        type: string
      sale_open_date:
        example: "2021-12-26T00:00:00Z"
        type: string
    required:
    - amount
    - name
    - price
    - sale_close_date
    - sale_open_date
    type: object
  request.ProductCategoryRequest:
    properties:
      description:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  request.TokenReqBody:
    properties:
      refresh_token:
        type: string
    type: object
  request.UpdateProductCategory:
    properties:
      description:
        type: string
      name:
        type: string
    type: object
  request.UserRequest:
    properties:
      avatar:
        example: admin
        type: string
      fullname:
        example: admin test
        type: string
      password:
        example: "1234"
        type: string
      username:
        example: admin
        type: string
    required:
    - fullname
    - password
    - username
    type: object
  response.CreateDataResponse:
    properties:
      message:
        example: create success
        type: string
      response_key:
        type: string
      response_message:
        type: string
    type: object
  response.DeleteDataResponse:
    properties:
      message:
        example: delete success
        type: string
      response_key:
        type: string
      response_message:
        type: string
    type: object
  response.Product:
    properties:
      description:
        example: apple
        type: string
      id:
        type: integer
      name:
        example: apple
        type: string
    required:
    - name
    type: object
  response.ProductCategory:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  response.ProductCategoryPagination:
    properties:
      data:
        items:
          $ref: '#/definitions/response.ProductCategory'
        type: array
      page:
        type: integer
      pageSize:
        type: integer
      response_key:
        type: string
      response_message:
        type: string
      totalPage:
        type: integer
    type: object
  response.ProductPagination:
    properties:
      data:
        items:
          $ref: '#/definitions/response.Product'
        type: array
      page:
        type: integer
      pageSize:
        type: integer
      response_key:
        type: string
      response_message:
        type: string
      totalPage:
        type: integer
    type: object
  response.UpdateDataResponse:
    properties:
      message:
        example: update success
        type: string
      response_key:
        type: string
      response_message:
        type: string
    type: object
  response.User:
    properties:
      avatar:
        type: string
      fullName:
        description: Password string `json:"password"`
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
  response.UserPagination:
    properties:
      data:
        items:
          $ref: '#/definitions/response.User'
        type: array
      page:
        type: integer
      pageSize:
        type: integer
      response_key:
        type: string
      response_message:
        type: string
      totalPage:
        type: integer
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      description: Login
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: Login
      tags:
      - Auth
  /auth/refresh/token:
    post:
      description: RefreshToken
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.TokenReqBody'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: RefreshToken
      tags:
      - Auth
  /auth/register:
    post:
      description: Register
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UserRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: Register
      tags:
      - Auth
  /products:
    get:
      description: Get List Products
      parameters:
      - description: int valid
        in: query
        name: page
        type: integer
      - description: int valid
        in: query
        name: pageSize
        type: integer
      - description: string valid
        in: query
        name: sortField
        type: string
      - description: string valid
        in: query
        name: sortValue
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ProductPagination'
      security:
      - Bearer: []
      summary: Get List Products
      tags:
      - Product
    post:
      description: Create Product
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.Product'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CreateDataResponse'
      security:
      - Bearer: []
      summary: Create Product
      tags:
      - Product
  /products/categories:
    get:
      description: Get List Product Category
      parameters:
      - description: int valid
        in: query
        name: page
        type: integer
      - description: int valid
        in: query
        name: pageSize
        type: integer
      - description: string valid
        in: query
        name: sortField
        type: string
      - description: string valid
        in: query
        name: sortValue
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ProductCategoryPagination'
      security:
      - Bearer: []
      summary: Get List product category
      tags:
      - Product Category
    post:
      description: Create Product Category
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.ProductCategoryRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CreateDataResponse'
      security:
      - Bearer: []
      summary: Create product category
      tags:
      - Product Category
  /products/categories/{productCategoryID}:
    delete:
      description: Delete product category By Id
      parameters:
      - description: User ID
        in: path
        name: productCategoryID
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UpdateDataResponse'
      security:
      - Bearer: []
      summary: Delete product category By Id
      tags:
      - Product Category
    get:
      description: Get product category By Id
      parameters:
      - description: User ID
        in: path
        name: productCategoryID
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ProductCategory'
      security:
      - Bearer: []
      summary: Get product category By Id
      tags:
      - Product Category
    put:
      description: Update product category By Id
      parameters:
      - description: User ID
        in: path
        name: productCategoryID
        required: true
        type: integer
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UpdateProductCategory'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UpdateDataResponse'
      security:
      - Bearer: []
      summary: Update product category By Id
      tags:
      - Product Category
  /users:
    get:
      description: Get List Users
      parameters:
      - description: int valid
        in: query
        name: page
        type: integer
      - description: int valid
        in: query
        name: pageSize
        type: integer
      - description: string valid
        in: query
        name: sortField
        type: string
      - description: string valid
        in: query
        name: sortValue
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserPagination'
      security:
      - Bearer: []
      summary: Get List Users
      tags:
      - User
    post:
      description: Create user
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UserRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CreateDataResponse'
      security:
      - Bearer: []
      summary: Create user
      tags:
      - User
  /users/{userID}:
    delete:
      description: Delete user By Id
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.DeleteDataResponse'
      security:
      - Bearer: []
      summary: Delete user By Id
      tags:
      - User
    get:
      description: Get user By Id
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.User'
      security:
      - Bearer: []
      summary: Get user By Id
      tags:
      - User
    put:
      description: Update user By Id
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: integer
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UserRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UpdateDataResponse'
      security:
      - Bearer: []
      summary: Update user By Id
      tags:
      - User
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
